version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/included:13.7.3
    working_directory: ~/repo

jobs:
  test:
    executor: cypress-executor
    parallelism: 4
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Cypress tests in parallel
          command: |
            TESTFILES=$(circleci tests glob "cypress/e2e/**/*.cy.js" | circleci tests split)
            SPECS=$(echo "$TESTFILES" | paste -sd, -)
            echo "Running specs: $SPECS"
            npx cypress run --spec "$SPECS"

workflows:
  version: 2
  run-tests:
    jobs:
      - test
