version: 2.1

parameters:
  env:
    type: string
    default: "dev"   # default value if none is selected

jobs:
  cypress-run:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Cypress Tests
          command: |
            if [ "<< pipeline.parameters.env >>" = "prod" ]; then
              npx cypress run --config-file cypress.config.prod.js
            else
              npx cypress run --config-file cypress.config.dev.js
            fi

workflows:
  cypress_workflow:
    jobs:
      - cypress-run
